### ISSUE TITLE
Can't build on Xcode 15.0 macOS 14.5: Cannot find 'kAudioAggregateDevicePropertyTapList' in scope

### ISSUE THREAD

**Issue by angstsmurf** [sbooth/CAAudioHardware#66]
Got this when trying to build SimplePlayer-macOS.

Sounds similar to this, but the answers are not helpful:
https://stackoverflow.com/questions/70552206/swift-unable-to-find-in-scope

I'm new to this so probably missing something obvious.
[Build CAAudioHardware_2024-07-27T13-32-59.txt](https://github.com/user-attachments/files/16399121/Build.CAAudioHardware_2024-07-27T13-32-59.txt)

**Comment by sbooth** [comment]
According to [Apple's docs](https://developer.apple.com/documentation/coreaudio/1545875-anonymous/kaudioaggregatedevicepropertytaplist) `kAudioAggregateDevicePropertyTapList` (and the other properties causing errors in your build) was added in macOS 14.2 but unfortunately those constants aren't decorated with availability macros in the CoreAudio headers. I would expect Xcode 15 to have those definitions in the SDK for macOS 14.5 but apparently that isn't the case. I will investigate a fix, but upgrading to a newer Xcode should also fix the problem.

**Comment by angstsmurf** [comment]
Thanks!

So this was pretty much a duplicate of https://github.com/sbooth/SFBAudioEngine/issues/268, in other words.

I'll try to make room on my HDD to update Xcode and report back.

**Comment by angstsmurf** [comment]
I can confirm that it works fine with Xcode 15.4. Closing this.
